CREATE OR REPLACE TASK MAILSHAKE_API.MAIL_API.OPENS_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('MAILSHAKE_API.MAIL_API.OPENS_STREAM')
AS
  CALL MAILSHAKE_API.MAIL_API.OPENS_SP();

CREATE OR REPLACE TASK MAILSHAKE_API.MAIL_API.CLICKS_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('MAILSHAKE_API.MAIL_API.CLICKS_STREAM')
AS
  CALL MAILSHAKE_API.MAIL_API.CLICKS_SP();

CREATE OR REPLACE TASK MAILSHAKE_API.MAIL_API.CREATED_LEADS_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('MAILSHAKE_API.MAIL_API.CREATED_LEADS_STREAM')
AS
  CALL MAILSHAKE_API.MAIL_API.CREATED_LEADS_SP();

CREATE OR REPLACE TASK MAILSHAKE_API.MAIL_API.REPLIES_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('MAILSHAKE_API.MAIL_API.REPLIES_STREAM')
AS
  CALL MAILSHAKE_API.MAIL_API.REPLIES_SP();

CREATE OR REPLACE TASK MAILSHAKE_API.MAIL_API.SENT_TASK
  WAREHOUSE = COMPUTE_WH
  WHEN SYSTEM$STREAM_HAS_DATA('MAILSHAKE_API.MAIL_API.SENT_STREAM')
AS
  CALL MAILSHAKE_API.MAIL_API.SENT_SP();

CREATE OR REPLACE TASK MAILSHAKE_API.MAIL_API.PURGE_RAW_TABLES_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 3 * * * UTC'  -- runs daily at 3 AM UTC
AS

BEGIN

-- OPENS
DELETE FROM MAILSHAKE_API.MAIL_API.ACTIVITY_OPENS
WHERE TRY_TO_TIMESTAMP_NTZ(ACTIONDATE) < DATEADD(DAY, -30, CURRENT_TIMESTAMP());

-- CLICKS
DELETE FROM MAILSHAKE_API.MAIL_API.ACTIVITY_CLICKS
WHERE TRY_TO_TIMESTAMP_NTZ(ACTIONDATE) < DATEADD(DAY, -30, CURRENT_TIMESTAMP());

-- REPLIES
DELETE FROM MAILSHAKE_API.MAIL_API.ACTIVITY_REPLIES
WHERE TRY_TO_TIMESTAMP_NTZ(ACTIONDATE) < DATEADD(DAY, -30, CURRENT_TIMESTAMP());

-- SENT
DELETE FROM MAILSHAKE_API.MAIL_API.ACTIVITY_SENT
WHERE TRY_TO_TIMESTAMP_NTZ(ACTIONDATE) < DATEADD(DAY, -30, CURRENT_TIMESTAMP());

-- CREATED LEADS (uses recipient_created instead of actiondate)
DELETE FROM MAILSHAKE_API.MAIL_API.ACTIVITY_CREATED_LEADS
WHERE TRY_TO_TIMESTAMP_NTZ(RECIPIENT_CREATED) < DATEADD(DAY, -30, CURRENT_TIMESTAMP());

END;
