CREATE OR REPLACE PROCEDURE MAILSHAKE_API.MAIL_API.OPENS_SP()
RETURNS VARCHAR(50)
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
try {
    snowflake.execute({sqlText: `BEGIN TRANSACTION;`});

    snowflake.execute({sqlText: `
        CREATE OR REPLACE TEMPORARY TABLE MAILSHAKE_API.MAIL_API.OPENS_TEMP AS
        SELECT
            TEAM_ID,
            OBJECT,
            ID,
            ACTIONDATE,
            ISDUPLICATE,
            RECIPIENT_OBJECT,
            RECIPIENT_ID,
            RECIPIENT_EMAILADDRESS,
            RECIPIENT_FULLNAME,
            RECIPIENT_CREATED,
            RECIPIENT_ISPAUSED,
            RECIPIENT_CONTACTID,
            RECIPIENT_FIRST,
            RECIPIENT_LAST,
            RECIPIENT_FIELDS_LINK,
            RECIPIENT_FIELDS_POSITION,
            RECIPIENT_FIELDS_DATE_APPLIED,
            RECIPIENT_FIELDS_ACCOUNT,
            RECIPIENT_FIELDS_PHONENUMBER,
            RECIPIENT_FIELDS_FACEBOOKURL,
            RECIPIENT_FIELDS_INSTAGRAMID,
            RECIPIENT_FIELDS_LINKEDINURL,
            RECIPIENT_FIELDS_TWITTERID,
            CAMPAIGN_OBJECT,
            CAMPAIGN_ID,
            CAMPAIGN_TITLE,
            CAMPAIGN_WIZARDSTATUS,
            PARENT_OBJECT,
            PARENT_ID,
            PARENT_TYPE,
            PARENT_MESSAGE_OBJECT,
            PARENT_MESSAGE_ID,
            PARENT_MESSAGE_TYPE,
            PARENT_MESSAGE_SUBJECT,
            PARENT_MESSAGE_REPLYTOID
        FROM MAILSHAKE_API.MAIL_API.OPENS_STREAM;
    `});

    snowflake.execute({sqlText: `
        MERGE INTO MAILSHAKE_API.MAIL_API.ACTIVITY_OPENS_TGT TGT
        USING MAILSHAKE_API.MAIL_API.OPENS_TEMP TMP
          ON TGT.TEAM_ID = TMP.TEAM_ID
         AND TGT.ID = TMP.ID
        WHEN MATCHED THEN UPDATE SET
            TGT.OBJECT = TMP.OBJECT,
            TGT.ACTIONDATE = TMP.ACTIONDATE,
            TGT.ISDUPLICATE = TMP.ISDUPLICATE,
            TGT.RECIPIENT_OBJECT = TMP.RECIPIENT_OBJECT,
            TGT.RECIPIENT_ID = TMP.RECIPIENT_ID,
            TGT.RECIPIENT_EMAILADDRESS = TMP.RECIPIENT_EMAILADDRESS,
            TGT.RECIPIENT_FULLNAME = TMP.RECIPIENT_FULLNAME,
            TGT.RECIPIENT_CREATED = TMP.RECIPIENT_CREATED,
            TGT.RECIPIENT_ISPAUSED = TMP.RECIPIENT_ISPAUSED,
            TGT.RECIPIENT_CONTACTID = TMP.RECIPIENT_CONTACTID,
            TGT.RECIPIENT_FIRST = TMP.RECIPIENT_FIRST,
            TGT.RECIPIENT_LAST = TMP.RECIPIENT_LAST,
            TGT.RECIPIENT_FIELDS_LINK = TMP.RECIPIENT_FIELDS_LINK,
            TGT.RECIPIENT_FIELDS_POSITION = TMP.RECIPIENT_FIELDS_POSITION,
            TGT.RECIPIENT_FIELDS_DATE_APPLIED = TMP.RECIPIENT_FIELDS_DATE_APPLIED,
            TGT.RECIPIENT_FIELDS_ACCOUNT = TMP.RECIPIENT_FIELDS_ACCOUNT,
            TGT.RECIPIENT_FIELDS_PHONENUMBER = TMP.RECIPIENT_FIELDS_PHONENUMBER,
            TGT.RECIPIENT_FIELDS_FACEBOOKURL = TMP.RECIPIENT_FIELDS_FACEBOOKURL,
            TGT.RECIPIENT_FIELDS_INSTAGRAMID = TMP.RECIPIENT_FIELDS_INSTAGRAMID,
            TGT.RECIPIENT_FIELDS_LINKEDINURL = TMP.RECIPIENT_FIELDS_LINKEDINURL,
            TGT.RECIPIENT_FIELDS_TWITTERID = TMP.RECIPIENT_FIELDS_TWITTERID,
            TGT.CAMPAIGN_OBJECT = TMP.CAMPAIGN_OBJECT,
            TGT.CAMPAIGN_ID = TMP.CAMPAIGN_ID,
            TGT.CAMPAIGN_TITLE = TMP.CAMPAIGN_TITLE,
            TGT.CAMPAIGN_WIZARDSTATUS = TMP.CAMPAIGN_WIZARDSTATUS,
            TGT.PARENT_OBJECT = TMP.PARENT_OBJECT,
            TGT.PARENT_ID = TMP.PARENT_ID,
            TGT.PARENT_TYPE = TMP.PARENT_TYPE,
            TGT.PARENT_MESSAGE_OBJECT = TMP.PARENT_MESSAGE_OBJECT,
            TGT.PARENT_MESSAGE_ID = TMP.PARENT_MESSAGE_ID,
            TGT.PARENT_MESSAGE_TYPE = TMP.PARENT_MESSAGE_TYPE,
            TGT.PARENT_MESSAGE_SUBJECT = TMP.PARENT_MESSAGE_SUBJECT,
            TGT.PARENT_MESSAGE_REPLYTOID = TMP.PARENT_MESSAGE_REPLYTOID,
            TGT.UPDATE_DTS = CURRENT_TIMESTAMP()
        WHEN NOT MATCHED THEN INSERT (
            TEAM_ID,
            OBJECT,
            ID,
            ACTIONDATE,
            ISDUPLICATE,
            RECIPIENT_OBJECT,
            RECIPIENT_ID,
            RECIPIENT_EMAILADDRESS,
            RECIPIENT_FULLNAME,
            RECIPIENT_CREATED,
            RECIPIENT_ISPAUSED,
            RECIPIENT_CONTACTID,
            RECIPIENT_FIRST,
            RECIPIENT_LAST,
            RECIPIENT_FIELDS_LINK,
            RECIPIENT_FIELDS_POSITION,
            RECIPIENT_FIELDS_DATE_APPLIED,
            RECIPIENT_FIELDS_ACCOUNT,
            RECIPIENT_FIELDS_PHONENUMBER,
            RECIPIENT_FIELDS_FACEBOOKURL,
            RECIPIENT_FIELDS_INSTAGRAMID,
            RECIPIENT_FIELDS_LINKEDINURL,
            RECIPIENT_FIELDS_TWITTERID,
            CAMPAIGN_OBJECT,
            CAMPAIGN_ID,
            CAMPAIGN_TITLE,
            CAMPAIGN_WIZARDSTATUS,
            PARENT_OBJECT,
            PARENT_ID,
            PARENT_TYPE,
            PARENT_MESSAGE_OBJECT,
            PARENT_MESSAGE_ID,
            PARENT_MESSAGE_TYPE,
            PARENT_MESSAGE_SUBJECT,
            PARENT_MESSAGE_REPLYTOID,
            INSERT_DTS,
            UPDATE_DTS
        ) VALUES (
            TMP.TEAM_ID,
            TMP.OBJECT,
            TMP.ID,
            TMP.ACTIONDATE,
            TMP.ISDUPLICATE,
            TMP.RECIPIENT_OBJECT,
            TMP.RECIPIENT_ID,
            TMP.RECIPIENT_EMAILADDRESS,
            TMP.RECIPIENT_FULLNAME,
            TMP.RECIPIENT_CREATED,
            TMP.RECIPIENT_ISPAUSED,
            TMP.RECIPIENT_CONTACTID,
            TMP.RECIPIENT_FIRST,
            TMP.RECIPIENT_LAST,
            TMP.RECIPIENT_FIELDS_LINK,
            TMP.RECIPIENT_FIELDS_POSITION,
            TMP.RECIPIENT_FIELDS_DATE_APPLIED,
            TMP.RECIPIENT_FIELDS_ACCOUNT,
            TMP.RECIPIENT_FIELDS_PHONENUMBER,
            TMP.RECIPIENT_FIELDS_FACEBOOKURL,
            TMP.RECIPIENT_FIELDS_INSTAGRAMID,
            TMP.RECIPIENT_FIELDS_LINKEDINURL,
            TMP.RECIPIENT_FIELDS_TWITTERID,
            TMP.CAMPAIGN_OBJECT,
            TMP.CAMPAIGN_ID,
            TMP.CAMPAIGN_TITLE,
            TMP.CAMPAIGN_WIZARDSTATUS,
            TMP.PARENT_OBJECT,
            TMP.PARENT_ID,
            TMP.PARENT_TYPE,
            TMP.PARENT_MESSAGE_OBJECT,
            TMP.PARENT_MESSAGE_ID,
            TMP.PARENT_MESSAGE_TYPE,
            TMP.PARENT_MESSAGE_SUBJECT,
            TMP.PARENT_MESSAGE_REPLYTOID,
            CURRENT_TIMESTAMP(),
            CURRENT_TIMESTAMP()
        );
    `});

    snowflake.execute({sqlText: `COMMIT;`});
    return 'OPENS_SP executed successfully';
} catch (err) {
    snowflake.execute({sqlText: `ROLLBACK;`});
    throw 'Error: ' + err;
}
$$;


CREATE OR REPLACE PROCEDURE MAILSHAKE_API.MAIL_API.CLICKS_SP()
RETURNS VARCHAR(50)
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
try {
    snowflake.execute({sqlText: `BEGIN TRANSACTION;`});

    snowflake.execute({sqlText: `
        CREATE OR REPLACE TEMPORARY TABLE MAILSHAKE_API.MAIL_API.CLICKS_TEMP AS
        SELECT
            TEAM_ID,
            OBJECT,
            ID,
            LINK,
            ACTIONDATE,
            ISDUPLICATE,
            RECIPIENT_OBJECT,
            RECIPIENT_ID,
            RECIPIENT_EMAILADDRESS,
            RECIPIENT_FULLNAME,
            RECIPIENT_CREATED,
            RECIPIENT_ISPAUSED,
            RECIPIENT_CONTACTID,
            RECIPIENT_FIRST,
            RECIPIENT_LAST,
            RECIPIENT_FIELDS_CITY,
            RECIPIENT_FIELDS_LAST,
            RECIPIENT_FIELDS_FIRST,
            RECIPIENT_FIELDS_STATE,
            RECIPIENT_FIELDS_FULL_NAME,
            RECIPIENT_FIELDS_PHONENUMBER,
            RECIPIENT_FIELDS_LINKEDINURL,
            CAMPAIGN_OBJECT,
            CAMPAIGN_ID,
            CAMPAIGN_TITLE,
            PARENT_OBJECT,
            PARENT_ID,
            PARENT_TYPE,
            PARENT_MESSAGE_OBJECT,
            PARENT_MESSAGE_ID,
            PARENT_MESSAGE_TYPE,
            PARENT_MESSAGE_SUBJECT,
            PARENT_MESSAGE_REPLYTOID,
            RECIPIENT_FIELDS_PHONE_2_COM
        FROM MAILSHAKE_API.MAIL_API.CLICKS_STREAM;
    `});

    snowflake.execute({sqlText: `
        MERGE INTO MAILSHAKE_API.MAIL_API.ACTIVITY_CLICKS_TGT TGT
        USING MAILSHAKE_API.MAIL_API.CLICKS_TEMP TMP
          ON TGT.TEAM_ID = TMP.TEAM_ID
         AND TGT.ID = TMP.ID
        WHEN MATCHED THEN UPDATE SET
            TGT.OBJECT = TMP.OBJECT,
            TGT.LINK = TMP.LINK,
            TGT.ACTIONDATE = TMP.ACTIONDATE,
            TGT.ISDUPLICATE = TMP.ISDUPLICATE,
            TGT.RECIPIENT_OBJECT = TMP.RECIPIENT_OBJECT,
            TGT.RECIPIENT_ID = TMP.RECIPIENT_ID,
            TGT.RECIPIENT_EMAILADDRESS = TMP.RECIPIENT_EMAILADDRESS,
            TGT.RECIPIENT_FULLNAME = TMP.RECIPIENT_FULLNAME,
            TGT.RECIPIENT_CREATED = TMP.RECIPIENT_CREATED,
            TGT.RECIPIENT_ISPAUSED = TMP.RECIPIENT_ISPAUSED,
            TGT.RECIPIENT_CONTACTID = TMP.RECIPIENT_CONTACTID,
            TGT.RECIPIENT_FIRST = TMP.RECIPIENT_FIRST,
            TGT.RECIPIENT_LAST = TMP.RECIPIENT_LAST,
            TGT.RECIPIENT_FIELDS_CITY = TMP.RECIPIENT_FIELDS_CITY,
            TGT.RECIPIENT_FIELDS_LAST = TMP.RECIPIENT_FIELDS_LAST,
            TGT.RECIPIENT_FIELDS_FIRST = TMP.RECIPIENT_FIELDS_FIRST,
            TGT.RECIPIENT_FIELDS_STATE = TMP.RECIPIENT_FIELDS_STATE,
            TGT.RECIPIENT_FIELDS_FULL_NAME = TMP.RECIPIENT_FIELDS_FULL_NAME,
            TGT.RECIPIENT_FIELDS_PHONENUMBER = TMP.RECIPIENT_FIELDS_PHONENUMBER,
            TGT.RECIPIENT_FIELDS_LINKEDINURL = TMP.RECIPIENT_FIELDS_LINKEDINURL,
            TGT.CAMPAIGN_OBJECT = TMP.CAMPAIGN_OBJECT,
            TGT.CAMPAIGN_ID = TMP.CAMPAIGN_ID,
            TGT.CAMPAIGN_TITLE = TMP.CAMPAIGN_TITLE,
            TGT.PARENT_OBJECT = TMP.PARENT_OBJECT,
            TGT.PARENT_ID = TMP.PARENT_ID,
            TGT.PARENT_TYPE = TMP.PARENT_TYPE,
            TGT.PARENT_MESSAGE_OBJECT = TMP.PARENT_MESSAGE_OBJECT,
            TGT.PARENT_MESSAGE_ID = TMP.PARENT_MESSAGE_ID,
            TGT.PARENT_MESSAGE_TYPE = TMP.PARENT_MESSAGE_TYPE,
            TGT.PARENT_MESSAGE_SUBJECT = TMP.PARENT_MESSAGE_SUBJECT,
            TGT.PARENT_MESSAGE_REPLYTOID = TMP.PARENT_MESSAGE_REPLYTOID,
            TGT.RECIPIENT_FIELDS_PHONE_2_COM = TMP.RECIPIENT_FIELDS_PHONE_2_COM,
            TGT.UPDATE_DTS = CURRENT_TIMESTAMP()
        WHEN NOT MATCHED THEN INSERT (
            TEAM_ID,
            OBJECT,
            ID,
            LINK,
            ACTIONDATE,
            ISDUPLICATE,
            RECIPIENT_OBJECT,
            RECIPIENT_ID,
            RECIPIENT_EMAILADDRESS,
            RECIPIENT_FULLNAME,
            RECIPIENT_CREATED,
            RECIPIENT_ISPAUSED,
            RECIPIENT_CONTACTID,
            RECIPIENT_FIRST,
            RECIPIENT_LAST,
            RECIPIENT_FIELDS_CITY,
            RECIPIENT_FIELDS_LAST,
            RECIPIENT_FIELDS_FIRST,
            RECIPIENT_FIELDS_STATE,
            RECIPIENT_FIELDS_FULL_NAME,
            RECIPIENT_FIELDS_PHONENUMBER,
            RECIPIENT_FIELDS_LINKEDINURL,
            CAMPAIGN_OBJECT,
            CAMPAIGN_ID,
            CAMPAIGN_TITLE,
            PARENT_OBJECT,
            PARENT_ID,
            PARENT_TYPE,
            PARENT_MESSAGE_OBJECT,
            PARENT_MESSAGE_ID,
            PARENT_MESSAGE_TYPE,
            PARENT_MESSAGE_SUBJECT,
            PARENT_MESSAGE_REPLYTOID,
            RECIPIENT_FIELDS_PHONE_2_COM,
            INSERT_DTS,
            UPDATE_DTS
        ) VALUES (
            TMP.TEAM_ID,
            TMP.OBJECT,
            TMP.ID,
            TMP.LINK,
            TMP.ACTIONDATE,
            TMP.ISDUPLICATE,
            TMP.RECIPIENT_OBJECT,
            TMP.RECIPIENT_ID,
            TMP.RECIPIENT_EMAILADDRESS,
            TMP.RECIPIENT_FULLNAME,
            TMP.RECIPIENT_CREATED,
            TMP.RECIPIENT_ISPAUSED,
            TMP.RECIPIENT_CONTACTID,
            TMP.RECIPIENT_FIRST,
            TMP.RECIPIENT_LAST,
            TMP.RECIPIENT_FIELDS_CITY,
            TMP.RECIPIENT_FIELDS_LAST,
            TMP.RECIPIENT_FIELDS_FIRST,
            TMP.RECIPIENT_FIELDS_STATE,
            TMP.RECIPIENT_FIELDS_FULL_NAME,
            TMP.RECIPIENT_FIELDS_PHONENUMBER,
            TMP.RECIPIENT_FIELDS_LINKEDINURL,
            TMP.CAMPAIGN_OBJECT,
            TMP.CAMPAIGN_ID,
            TMP.CAMPAIGN_TITLE,
            TMP.PARENT_OBJECT,
            TMP.PARENT_ID,
            TMP.PARENT_TYPE,
            TMP.PARENT_MESSAGE_OBJECT,
            TMP.PARENT_MESSAGE_ID,
            TMP.PARENT_MESSAGE_TYPE,
            TMP.PARENT_MESSAGE_SUBJECT,
            TMP.PARENT_MESSAGE_REPLYTOID,
            TMP.RECIPIENT_FIELDS_PHONE_2_COM,
            CURRENT_TIMESTAMP(),
            CURRENT_TIMESTAMP()
        );
    `});

    snowflake.execute({sqlText: `COMMIT;`});
    return 'CLICKS_SP executed successfully';
} catch (err) {
    snowflake.execute({sqlText: `ROLLBACK;`});
    throw 'Error: ' + err;
}
$$;


CREATE OR REPLACE PROCEDURE MAILSHAKE_API.MAIL_API.CREATED_LEADS_SP()
RETURNS VARCHAR(50)
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
try {
    snowflake.execute({sqlText: `BEGIN TRANSACTION;`});

    snowflake.execute({sqlText: `
        CREATE OR REPLACE TEMPORARY TABLE MAILSHAKE_API.MAIL_API.CREATED_LEADS_TEMP AS
        SELECT
            TEAM_ID,
            OBJECT,
            ID,
            RECIPIENT_OBJECT,
            RECIPIENT_ID,
            RECIPIENT_EMAILADDRESS,
            RECIPIENT_FULLNAME,
            RECIPIENT_CREATED,
            RECIPIENT_ISPAUSED,
            RECIPIENT_CONTACTID,
            RECIPIENT_FIRST,
            RECIPIENT_LAST,
            RECIPIENT_FIELDS_ID,
            RECIPIENT_FIELDS_EMAILADDRESS,
            RECIPIENT_FIELDS_FIRST,
            RECIPIENT_FIELDS_LAST,
            RECIPIENT_FIELDS_LINKEDINURL,
            RECIPIENT_FIELDS_POSITION,
            RECIPIENT_FIELDS_DATE_APPLIED,
            RECIPIENT_FIELDS_ACCOUNT,
            CAMPAIGN_OBJECT,
            CAMPAIGN_ID,
            CAMPAIGN_TITLE,
            CAMPAIGN_WIZARDSTATUS
        FROM MAILSHAKE_API.MAIL_API.CREATED_LEADS_STREAM;
    `});

    snowflake.execute({sqlText: `
        MERGE INTO MAILSHAKE_API.MAIL_API.ACTIVITY_CREATED_LEADS_TGT TGT
        USING MAILSHAKE_API.MAIL_API.CREATED_LEADS_TEMP TMP
          ON TGT.TEAM_ID = TMP.TEAM_ID
         AND TGT.ID = TMP.ID
        WHEN MATCHED THEN UPDATE SET
            TGT.OBJECT = TMP.OBJECT,
            TGT.RECIPIENT_OBJECT = TMP.RECIPIENT_OBJECT,
            TGT.RECIPIENT_ID = TMP.RECIPIENT_ID,
            TGT.RECIPIENT_EMAILADDRESS = TMP.RECIPIENT_EMAILADDRESS,
            TGT.RECIPIENT_FULLNAME = TMP.RECIPIENT_FULLNAME,
            TGT.RECIPIENT_CREATED = TMP.RECIPIENT_CREATED,
            TGT.RECIPIENT_ISPAUSED = TMP.RECIPIENT_ISPAUSED,
            TGT.RECIPIENT_CONTACTID = TMP.RECIPIENT_CONTACTID,
            TGT.RECIPIENT_FIRST = TMP.RECIPIENT_FIRST,
            TGT.RECIPIENT_LAST = TMP.RECIPIENT_LAST,
            TGT.RECIPIENT_FIELDS_ID = TMP.RECIPIENT_FIELDS_ID,
            TGT.RECIPIENT_FIELDS_EMAILADDRESS = TMP.RECIPIENT_FIELDS_EMAILADDRESS,
            TGT.RECIPIENT_FIELDS_FIRST = TMP.RECIPIENT_FIELDS_FIRST,
            TGT.RECIPIENT_FIELDS_LAST = TMP.RECIPIENT_FIELDS_LAST,
            TGT.RECIPIENT_FIELDS_LINKEDINURL = TMP.RECIPIENT_FIELDS_LINKEDINURL,
            TGT.RECIPIENT_FIELDS_POSITION = TMP.RECIPIENT_FIELDS_POSITION,
            TGT.RECIPIENT_FIELDS_DATE_APPLIED = TMP.RECIPIENT_FIELDS_DATE_APPLIED,
            TGT.RECIPIENT_FIELDS_ACCOUNT = TMP.RECIPIENT_FIELDS_ACCOUNT,
            TGT.CAMPAIGN_OBJECT = TMP.CAMPAIGN_OBJECT,
            TGT.CAMPAIGN_ID = TMP.CAMPAIGN_ID,
            TGT.CAMPAIGN_TITLE = TMP.CAMPAIGN_TITLE,
            TGT.CAMPAIGN_WIZARDSTATUS = TMP.CAMPAIGN_WIZARDSTATUS,
            TGT.UPDATE_DTS = CURRENT_TIMESTAMP()
        WHEN NOT MATCHED THEN INSERT (
            TEAM_ID,
            OBJECT,
            ID,
            RECIPIENT_OBJECT,
            RECIPIENT_ID,
            RECIPIENT_EMAILADDRESS,
            RECIPIENT_FULLNAME,
            RECIPIENT_CREATED,
            RECIPIENT_ISPAUSED,
            RECIPIENT_CONTACTID,
            RECIPIENT_FIRST,
            RECIPIENT_LAST,
            RECIPIENT_FIELDS_ID,
            RECIPIENT_FIELDS_EMAILADDRESS,
            RECIPIENT_FIELDS_FIRST,
            RECIPIENT_FIELDS_LAST,
            RECIPIENT_FIELDS_LINKEDINURL,
            RECIPIENT_FIELDS_POSITION,
            RECIPIENT_FIELDS_DATE_APPLIED,
            RECIPIENT_FIELDS_ACCOUNT,
            CAMPAIGN_OBJECT,
            CAMPAIGN_ID,
            CAMPAIGN_TITLE,
            CAMPAIGN_WIZARDSTATUS,
            INSERT_DTS,
            UPDATE_DTS
        ) VALUES (
            TMP.TEAM_ID,
            TMP.OBJECT,
            TMP.ID,
            TMP.RECIPIENT_OBJECT,
            TMP.RECIPIENT_ID,
            TMP.RECIPIENT_EMAILADDRESS,
            TMP.RECIPIENT_FULLNAME,
            TMP.RECIPIENT_CREATED,
            TMP.RECIPIENT_ISPAUSED,
            TMP.RECIPIENT_CONTACTID,
            TMP.RECIPIENT_FIRST,
            TMP.RECIPIENT_LAST,
            TMP.RECIPIENT_FIELDS_ID,
            TMP.RECIPIENT_FIELDS_EMAILADDRESS,
            TMP.RECIPIENT_FIELDS_FIRST,
            TMP.RECIPIENT_FIELDS_LAST,
            TMP.RECIPIENT_FIELDS_LINKEDINURL,
            TMP.RECIPIENT_FIELDS_POSITION,
            TMP.RECIPIENT_FIELDS_DATE_APPLIED,
            TMP.RECIPIENT_FIELDS_ACCOUNT,
            TMP.CAMPAIGN_OBJECT,
            TMP.CAMPAIGN_ID,
            TMP.CAMPAIGN_TITLE,
            TMP.CAMPAIGN_WIZARDSTATUS,
            CURRENT_TIMESTAMP(),
            CURRENT_TIMESTAMP()
        );
    `});

    snowflake.execute({sqlText: `COMMIT;`});
    return 'CREATED_LEADS_SP executed successfully';
} catch (err) {
    snowflake.execute({sqlText: `ROLLBACK;`});
    throw 'Error: ' + err;
}
$$;


CREATE OR REPLACE PROCEDURE MAILSHAKE_API.MAIL_API.REPLIES_SP()
RETURNS VARCHAR(50)
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
try {
    snowflake.execute({sqlText: `BEGIN TRANSACTION;`});

    snowflake.execute({sqlText: `
        CREATE OR REPLACE TEMPORARY TABLE MAILSHAKE_API.MAIL_API.REPLIES_TEMP AS
        SELECT
            TEAM_ID,
            OBJECT,
            ID,
            ACTIONDATE,
            TYPE,
            SUBJECT,
            PLAINTEXTBODY,
            RECIPIENT_OBJECT,
            RECIPIENT_ID,
            RECIPIENT_EMAILADDRESS,
            RECIPIENT_CREATED,
            RECIPIENT_ISPAUSED,
            RECIPIENT_CONTACTID,
            RECIPIENT_FIELDS_LINK,
            RECIPIENT_FIELDS_POSITION,
            RECIPIENT_FIELDS_DATE_APPLIED,
            RECIPIENT_FIELDS_ACCOUNT,
            RECIPIENT_FIELDS_LINKEDINURL,
            CAMPAIGN_OBJECT,
            CAMPAIGN_ID,
            CAMPAIGN_TITLE,
            CAMPAIGN_WIZARDSTATUS,
            PARENT_OBJECT,
            PARENT_ID,
            PARENT_TYPE,
            PARENT_MESSAGE_OBJECT,
            PARENT_MESSAGE_ID,
            PARENT_MESSAGE_TYPE,
            PARENT_MESSAGE_SUBJECT,
            PARENT_MESSAGE_REPLYTOID,
            FROM_OBJECT,
            FROM_ADDRESS
        FROM MAILSHAKE_API.MAIL_API.REPLIES_STREAM;
    `});

    snowflake.execute({sqlText: `
        MERGE INTO MAILSHAKE_API.MAIL_API.ACTIVITY_REPLIES_TGT TGT
        USING MAILSHAKE_API.MAIL_API.REPLIES_TEMP TMP
          ON TGT.TEAM_ID = TMP.TEAM_ID
         AND TGT.ID = TMP.ID
        WHEN MATCHED THEN UPDATE SET
            TGT.OBJECT = TMP.OBJECT,
            TGT.ACTIONDATE = TMP.ACTIONDATE,
            TGT.TYPE = TMP.TYPE,
            TGT.SUBJECT = TMP.SUBJECT,
            TGT.PLAINTEXTBODY = TMP.PLAINTEXTBODY,
            TGT.RECIPIENT_OBJECT = TMP.RECIPIENT_OBJECT,
            TGT.RECIPIENT_ID = TMP.RECIPIENT_ID,
            TGT.RECIPIENT_EMAILADDRESS = TMP.RECIPIENT_EMAILADDRESS,
            TGT.RECIPIENT_CREATED = TMP.RECIPIENT_CREATED,
            TGT.RECIPIENT_ISPAUSED = TMP.RECIPIENT_ISPAUSED,
            TGT.RECIPIENT_CONTACTID = TMP.RECIPIENT_CONTACTID,
            TGT.RECIPIENT_FIELDS_LINK = TMP.RECIPIENT_FIELDS_LINK,
            TGT.RECIPIENT_FIELDS_POSITION = TMP.RECIPIENT_FIELDS_POSITION,
            TGT.RECIPIENT_FIELDS_DATE_APPLIED = TMP.RECIPIENT_FIELDS_DATE_APPLIED,
            TGT.RECIPIENT_FIELDS_ACCOUNT = TMP.RECIPIENT_FIELDS_ACCOUNT,
            TGT.RECIPIENT_FIELDS_LINKEDINURL = TMP.RECIPIENT_FIELDS_LINKEDINURL,
            TGT.CAMPAIGN_OBJECT = TMP.CAMPAIGN_OBJECT,
            TGT.CAMPAIGN_ID = TMP.CAMPAIGN_ID,
            TGT.CAMPAIGN_TITLE = TMP.CAMPAIGN_TITLE,
            TGT.CAMPAIGN_WIZARDSTATUS = TMP.CAMPAIGN_WIZARDSTATUS,
            TGT.PARENT_OBJECT = TMP.PARENT_OBJECT,
            TGT.PARENT_ID = TMP.PARENT_ID,
            TGT.PARENT_TYPE = TMP.PARENT_TYPE,
            TGT.PARENT_MESSAGE_OBJECT = TMP.PARENT_MESSAGE_OBJECT,
            TGT.PARENT_MESSAGE_ID = TMP.PARENT_MESSAGE_ID,
            TGT.PARENT_MESSAGE_TYPE = TMP.PARENT_MESSAGE_TYPE,
            TGT.PARENT_MESSAGE_SUBJECT = TMP.PARENT_MESSAGE_SUBJECT,
            TGT.PARENT_MESSAGE_REPLYTOID = TMP.PARENT_MESSAGE_REPLYTOID,
            TGT.FROM_OBJECT = TMP.FROM_OBJECT,
            TGT.FROM_ADDRESS = TMP.FROM_ADDRESS,
            TGT.UPDATE_DTS = CURRENT_TIMESTAMP()
        WHEN NOT MATCHED THEN INSERT (
            TEAM_ID,
            OBJECT,
            ID,
            ACTIONDATE,
            TYPE,
            SUBJECT,
            PLAINTEXTBODY,
            RECIPIENT_OBJECT,
            RECIPIENT_ID,
            RECIPIENT_EMAILADDRESS,
            RECIPIENT_CREATED,
            RECIPIENT_ISPAUSED,
            RECIPIENT_CONTACTID,
            RECIPIENT_FIELDS_LINK,
            RECIPIENT_FIELDS_POSITION,
            RECIPIENT_FIELDS_DATE_APPLIED,
            RECIPIENT_FIELDS_ACCOUNT,
            RECIPIENT_FIELDS_LINKEDINURL,
            CAMPAIGN_OBJECT,
            CAMPAIGN_ID,
            CAMPAIGN_TITLE,
            CAMPAIGN_WIZARDSTATUS,
            PARENT_OBJECT,
            PARENT_ID,
            PARENT_TYPE,
            PARENT_MESSAGE_OBJECT,
            PARENT_MESSAGE_ID,
            PARENT_MESSAGE_TYPE,
            PARENT_MESSAGE_SUBJECT,
            PARENT_MESSAGE_REPLYTOID,
            FROM_OBJECT,
            FROM_ADDRESS,
            INSERT_DTS,
            UPDATE_DTS
        ) VALUES (
            TMP.TEAM_ID,
            TMP.OBJECT,
            TMP.ID,
            TMP.ACTIONDATE,
            TMP.TYPE,
            TMP.SUBJECT,
            TMP.PLAINTEXTBODY,
            TMP.RECIPIENT_OBJECT,
            TMP.RECIPIENT_ID,
            TMP.RECIPIENT_EMAILADDRESS,
            TMP.RECIPIENT_CREATED,
            TMP.RECIPIENT_ISPAUSED,
            TMP.RECIPIENT_CONTACTID,
            TMP.RECIPIENT_FIELDS_LINK,
            TMP.RECIPIENT_FIELDS_POSITION,
            TMP.RECIPIENT_FIELDS_DATE_APPLIED,
            TMP.RECIPIENT_FIELDS_ACCOUNT,
            TMP.RECIPIENT_FIELDS_LINKEDINURL,
            TMP.CAMPAIGN_OBJECT,
            TMP.CAMPAIGN_ID,
            TMP.CAMPAIGN_TITLE,
            TMP.CAMPAIGN_WIZARDSTATUS,
            TMP.PARENT_OBJECT,
            TMP.PARENT_ID,
            TMP.PARENT_TYPE,
            TMP.PARENT_MESSAGE_OBJECT,
            TMP.PARENT_MESSAGE_ID,
            TMP.PARENT_MESSAGE_TYPE,
            TMP.PARENT_MESSAGE_SUBJECT,
            TMP.PARENT_MESSAGE_REPLYTOID,
            TMP.FROM_OBJECT,
            TMP.FROM_ADDRESS,
            CURRENT_TIMESTAMP(),
            CURRENT_TIMESTAMP()
        );
    `});

    snowflake.execute({sqlText: `COMMIT;`});
    return 'REPLIES_SP executed successfully';
} catch (err) {
    snowflake.execute({sqlText: `ROLLBACK;`});
    throw 'Error: ' + err;
}
$$;


CREATE OR REPLACE PROCEDURE MAILSHAKE_API.MAIL_API.SENT_SP()
RETURNS VARCHAR(50)
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$
try {
    snowflake.execute({sqlText: `BEGIN TRANSACTION;`});

    snowflake.execute({sqlText: `
        CREATE OR REPLACE TEMPORARY TABLE MAILSHAKE_API.MAIL_API.SENT_TEMP AS
        SELECT
            TEAM_ID,
            OBJECT,
            ID,
            ACTIONDATE,
            RECIPIENT_OBJECT,
            RECIPIENT_ID,
            RECIPIENT_EMAILADDRESS,
            RECIPIENT_FULLNAME,
            RECIPIENT_CREATED,
            RECIPIENT_ISPAUSED,
            RECIPIENT_CONTACTID,
            RECIPIENT_FIRST,
            RECIPIENT_LAST,
            CAMPAIGN_OBJECT,
            CAMPAIGN_ID,
            CAMPAIGN_TITLE,
            CAMPAIGN_WIZARDSTATUS,
            MESSAGE_OBJECT,
            MESSAGE_ID,
            MESSAGE_SUBJECT,
            MESSAGE_BODY,
            MESSAGE_PLAINTEXTBODY,
            MESSAGE_RAWBODY,
            MESSAGE_REPLYTOID
        FROM MAILSHAKE_API.MAIL_API.SENT_STREAM;
    `});

    snowflake.execute({sqlText: `
        MERGE INTO MAILSHAKE_API.MAIL_API.ACTIVITY_SENT_TGT TGT
        USING MAILSHAKE_API.MAIL_API.SENT_TEMP TMP
          ON TGT.TEAM_ID = TMP.TEAM_ID
         AND TGT.ID = TMP.ID
        WHEN MATCHED THEN UPDATE SET
            TGT.OBJECT = TMP.OBJECT,
            TGT.ACTIONDATE = TMP.ACTIONDATE,
            TGT.RECIPIENT_OBJECT = TMP.RECIPIENT_OBJECT,
            TGT.RECIPIENT_ID = TMP.RECIPIENT_ID,
            TGT.RECIPIENT_EMAILADDRESS = TMP.RECIPIENT_EMAILADDRESS,
            TGT.RECIPIENT_FULLNAME = TMP.RECIPIENT_FULLNAME,
            TGT.RECIPIENT_CREATED = TMP.RECIPIENT_CREATED,
            TGT.RECIPIENT_ISPAUSED = TMP.RECIPIENT_ISPAUSED,
            TGT.RECIPIENT_CONTACTID = TMP.RECIPIENT_CONTACTID,
            TGT.RECIPIENT_FIRST = TMP.RECIPIENT_FIRST,
            TGT.RECIPIENT_LAST = TMP.RECIPIENT_LAST,
            TGT.CAMPAIGN_OBJECT = TMP.CAMPAIGN_OBJECT,
            TGT.CAMPAIGN_ID = TMP.CAMPAIGN_ID,
            TGT.CAMPAIGN_TITLE = TMP.CAMPAIGN_TITLE,
            TGT.CAMPAIGN_WIZARDSTATUS = TMP.CAMPAIGN_WIZARDSTATUS,
            TGT.MESSAGE_OBJECT = TMP.MESSAGE_OBJECT,
            TGT.MESSAGE_ID = TMP.MESSAGE_ID,
            TGT.MESSAGE_SUBJECT = TMP.MESSAGE_SUBJECT,
            TGT.MESSAGE_BODY = TMP.MESSAGE_BODY,
            TGT.MESSAGE_PLAINTEXTBODY = TMP.MESSAGE_PLAINTEXTBODY,
            TGT.MESSAGE_RAWBODY = TMP.MESSAGE_RAWBODY,
            TGT.MESSAGE_REPLYTOID = TMP.MESSAGE_REPLYTOID,
            TGT.UPDATE_DTS = CURRENT_TIMESTAMP()
        WHEN NOT MATCHED THEN INSERT (
            TEAM_ID,
            OBJECT,
            ID,
            ACTIONDATE,
            RECIPIENT_OBJECT,
            RECIPIENT_ID,
            RECIPIENT_EMAILADDRESS,
            RECIPIENT_FULLNAME,
            RECIPIENT_CREATED,
            RECIPIENT_ISPAUSED,
            RECIPIENT_CONTACTID,
            RECIPIENT_FIRST,
            RECIPIENT_LAST,
            CAMPAIGN_OBJECT,
            CAMPAIGN_ID,
            CAMPAIGN_TITLE,
            CAMPAIGN_WIZARDSTATUS,
            MESSAGE_OBJECT,
            MESSAGE_ID,
            MESSAGE_SUBJECT,
            MESSAGE_BODY,
            MESSAGE_PLAINTEXTBODY,
            MESSAGE_RAWBODY,
            MESSAGE_REPLYTOID,
            INSERT_DTS,
            UPDATE_DTS
        ) VALUES (
            TMP.TEAM_ID,
            TMP.OBJECT,
            TMP.ID,
            TMP.ACTIONDATE,
            TMP.RECIPIENT_OBJECT,
            TMP.RECIPIENT_ID,
            TMP.RECIPIENT_EMAILADDRESS,
            TMP.RECIPIENT_FULLNAME,
            TMP.RECIPIENT_CREATED,
            TMP.RECIPIENT_ISPAUSED,
            TMP.RECIPIENT_CONTACTID,
            TMP.RECIPIENT_FIRST,
            TMP.RECIPIENT_LAST,
            TMP.CAMPAIGN_OBJECT,
            TMP.CAMPAIGN_ID,
            TMP.CAMPAIGN_TITLE,
            TMP.CAMPAIGN_WIZARDSTATUS,
            TMP.MESSAGE_OBJECT,
            TMP.MESSAGE_ID,
            TMP.MESSAGE_SUBJECT,
            TMP.MESSAGE_BODY,
            TMP.MESSAGE_PLAINTEXTBODY,
            TMP.MESSAGE_RAWBODY,
            TMP.MESSAGE_REPLYTOID,
            CURRENT_TIMESTAMP(),
            CURRENT_TIMESTAMP()
        );
    `});

    snowflake.execute({sqlText: `COMMIT;`});
    return 'SENT_SP executed successfully';
} catch (err) {
    snowflake.execute({sqlText: `ROLLBACK;`});
    throw 'Error: ' + err;
}
$$;
