CREATE OR REPLACE PIPE MAILSHAKE_API.MAIL_API.ACTIVITY_OPENS_API_PIPE
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = 'arn:aws:sns:us-east-1:655691758300:snowpipe-sns-opens'
AS
COPY INTO MAILSHAKE_API.MAIL_API.ACTIVITY_OPENS
FROM (
    SELECT
        $1  AS TEAM_ID,
        $2  AS OBJECT,
        $3  AS ID,
        $4  AS ACTIONDATE,
        $5  AS ISDUPLICATE,
        $6  AS RECIPIENT_OBJECT,
        $7  AS RECIPIENT_ID,
        $8  AS RECIPIENT_EMAILADDRESS,
        $9  AS RECIPIENT_FULLNAME,
        $10 AS RECIPIENT_CREATED,
        $11 AS RECIPIENT_ISPAUSED,
        $12 AS RECIPIENT_CONTACTID,
        $13 AS RECIPIENT_FIRST,
        $14 AS RECIPIENT_LAST,
        $15 AS RECIPIENT_FIELDS_LINK,
        $16 AS RECIPIENT_FIELDS_POSITION,
        $17 AS RECIPIENT_FIELDS_DATE_APPLIED,
        $18 AS RECIPIENT_FIELDS_ACCOUNT,
        $19 AS RECIPIENT_FIELDS_PHONENUMBER,
        $20 AS RECIPIENT_FIELDS_FACEBOOKURL,
        $21 AS RECIPIENT_FIELDS_INSTAGRAMID,
        $22 AS RECIPIENT_FIELDS_LINKEDINURL,
        $23 AS RECIPIENT_FIELDS_TWITTERID,
        $24 AS CAMPAIGN_OBJECT,
        $25 AS CAMPAIGN_ID,
        $26 AS CAMPAIGN_TITLE,
        $27 AS CAMPAIGN_WIZARDSTATUS,
        $28 AS PARENT_OBJECT,
        $29 AS PARENT_ID,
        $30 AS PARENT_TYPE,
        $31 AS PARENT_MESSAGE_OBJECT,
        $32 AS PARENT_MESSAGE_ID,
        $33 AS PARENT_MESSAGE_TYPE,
        $34 AS PARENT_MESSAGE_SUBJECT,
        $35 AS PARENT_MESSAGE_REPLYTOID
    FROM @MAILSHAKE_API.MAIL_API.MAILSHAKE_API_STAGE/merged-opens/
)
FILE_FORMAT = (FORMAT_NAME = MAILSHAKE_API.MAIL_API.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE MAILSHAKE_API.MAIL_API.ACTIVITY_SENT_API_PIPE
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = 'arn:aws:sns:us-east-1:655691758300:snowpipe-sns-sent'
AS
COPY INTO MAILSHAKE_API.MAIL_API.ACTIVITY_SENT
FROM (
    SELECT
        $1  AS TEAM_ID,
        $2  AS OBJECT,
        $3  AS ID,
        $4  AS ACTIONDATE,
        $5  AS RECIPIENT_OBJECT,
        $6  AS RECIPIENT_ID,
        $7  AS RECIPIENT_EMAILADDRESS,
        $8  AS RECIPIENT_FULLNAME,
        $9  AS RECIPIENT_CREATED,
        $10 AS RECIPIENT_ISPAUSED,
        $11 AS RECIPIENT_CONTACTID,
        $12 AS RECIPIENT_FIRST,
        $13 AS RECIPIENT_LAST,
        $14 AS CAMPAIGN_OBJECT,
        $15 AS CAMPAIGN_ID,
        $16 AS CAMPAIGN_TITLE,
        $17 AS CAMPAIGN_WIZARDSTATUS,
        $18 AS MESSAGE_OBJECT,
        $19 AS MESSAGE_ID,
        $20 AS MESSAGE_SUBJECT,
        $21 AS MESSAGE_BODY,
        $22 AS MESSAGE_PLAINTEXTBODY,
        $23 AS MESSAGE_RAWBODY,
        $24 AS MESSAGE_REPLYTOID
    FROM @MAILSHAKE_API.MAIL_API.MAILSHAKE_API_STAGE/merged-sent/
)
FILE_FORMAT = (FORMAT_NAME = MAILSHAKE_API.MAIL_API.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE MAILSHAKE_API.MAIL_API.ACTIVITY_CLICKS_API_PIPE
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = 'arn:aws:sns:us-east-1:655691758300:snowpipe-sns-clicks'
AS
COPY INTO MAILSHAKE_API.MAIL_API.ACTIVITY_CLICKS
FROM (
    SELECT
        $1  AS TEAM_ID,
        $2  AS OBJECT,
        $3  AS ID,
        $4  AS LINK,
        $5  AS ACTIONDATE,
        $6  AS ISDUPLICATE,
        $7  AS RECIPIENT_OBJECT,
        $8  AS RECIPIENT_ID,
        $9  AS RECIPIENT_EMAILADDRESS,
        $10 AS RECIPIENT_FULLNAME,
        $11 AS RECIPIENT_CREATED,
        $12 AS RECIPIENT_ISPAUSED,
        $13 AS RECIPIENT_CONTACTID,
        $14 AS RECIPIENT_FIRST,
        $15 AS RECIPIENT_LAST,
        $16 AS RECIPIENT_FIELDS_CITY,
        $17 AS RECIPIENT_FIELDS_LAST,
        $18 AS RECIPIENT_FIELDS_FIRST,
        $19 AS RECIPIENT_FIELDS_STATE,
        $20 AS RECIPIENT_FIELDS_FULL_NAME,
        $21 AS RECIPIENT_FIELDS_PHONENUMBER,
        $22 AS RECIPIENT_FIELDS_LINKEDINURL,
        $23 AS CAMPAIGN_OBJECT,
        $24 AS CAMPAIGN_ID,
        $25 AS CAMPAIGN_TITLE,
        $26 AS PARENT_OBJECT,
        $27 AS PARENT_ID,
        $28 AS PARENT_TYPE,
        $29 AS PARENT_MESSAGE_OBJECT,
        $30 AS PARENT_MESSAGE_ID,
        $31 AS PARENT_MESSAGE_TYPE,
        $32 AS PARENT_MESSAGE_SUBJECT,
        $33 AS PARENT_MESSAGE_REPLYTOID,
        $34 AS RECIPIENT_FIELDS_PHONE_2_COM
    FROM @MAILSHAKE_API.MAIL_API.MAILSHAKE_API_STAGE/merged-clicks/
)
FILE_FORMAT = (FORMAT_NAME = MAILSHAKE_API.MAIL_API.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE MAILSHAKE_API.MAIL_API.ACTIVITY_REPLIES_API_PIPE
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = 'arn:aws:sns:us-east-1:655691758300:snowpipe-sns-replies'
AS
COPY INTO MAILSHAKE_API.MAIL_API.ACTIVITY_REPLIES
FROM (
    SELECT
        $1  AS TEAM_ID,
        $2  AS OBJECT,
        $3  AS ID,
        $4  AS ACTIONDATE,
        $5  AS TYPE,
        $6  AS SUBJECT,
        $7  AS PLAINTEXTBODY,
        $8  AS RECIPIENT_OBJECT,
        $9  AS RECIPIENT_ID,
        $10 AS RECIPIENT_EMAILADDRESS,
        $11 AS RECIPIENT_CREATED,
        $12 AS RECIPIENT_ISPAUSED,
        $13 AS RECIPIENT_CONTACTID,
        $14 AS RECIPIENT_FIELDS_LINK,
        $15 AS RECIPIENT_FIELDS_POSITION,
        $16 AS RECIPIENT_FIELDS_DATE_APPLIED,
        $17 AS RECIPIENT_FIELDS_ACCOUNT,
        $18 AS RECIPIENT_FIELDS_LINKEDINURL,
        $19 AS CAMPAIGN_OBJECT,
        $20 AS CAMPAIGN_ID,
        $21 AS CAMPAIGN_TITLE,
        $22 AS CAMPAIGN_WIZARDSTATUS,
        $23 AS PARENT_OBJECT,
        $24 AS PARENT_ID,
        $25 AS PARENT_TYPE,
        $26 AS PARENT_MESSAGE_OBJECT,
        $27 AS PARENT_MESSAGE_ID,
        $28 AS PARENT_MESSAGE_TYPE,
        $29 AS PARENT_MESSAGE_SUBJECT,
        $30 AS PARENT_MESSAGE_REPLYTOID,
        $31 AS FROM_OBJECT,
        $32 AS FROM_ADDRESS
    FROM @MAILSHAKE_API.MAIL_API.MAILSHAKE_API_STAGE/merged-replies/
)
FILE_FORMAT = (FORMAT_NAME = MAILSHAKE_API.MAIL_API.CSV_FORMAT)
ON_ERROR = 'CONTINUE';

CREATE OR REPLACE PIPE MAILSHAKE_API.MAIL_API.ACTIVITY_CREATED_LEADS_API_PIPE
AUTO_INGEST = TRUE
AWS_SNS_TOPIC = 'arn:aws:sns:us-east-1:655691758300:snowpipe-sns-created-leads'
AS
COPY INTO MAILSHAKE_API.MAIL_API.ACTIVITY_CREATED_LEADS
FROM (
    SELECT
        $1  AS TEAM_ID,
        $2  AS OBJECT,
        $3  AS ID,
        $4  AS RECIPIENT_OBJECT,
        $5  AS RECIPIENT_ID,
        $6  AS RECIPIENT_EMAILADDRESS,
        $7  AS RECIPIENT_FULLNAME,
        $8  AS RECIPIENT_CREATED,
        $9  AS RECIPIENT_ISPAUSED,
        $10 AS RECIPIENT_CONTACTID,
        $11 AS RECIPIENT_FIRST,
        $12 AS RECIPIENT_LAST,
        $13 AS RECIPIENT_FIELDS_ID,
        $14 AS RECIPIENT_FIELDS_EMAILADDRESS,
        $15 AS RECIPIENT_FIELDS_FIRST,
        $16 AS RECIPIENT_FIELDS_LAST,
        $17 AS RECIPIENT_FIELDS_LINKEDINURL,
        $18 AS RECIPIENT_FIELDS_POSITION,
        $19 AS RECIPIENT_FIELDS_DATE_APPLIED,
        $20 AS RECIPIENT_FIELDS_ACCOUNT,
        $21 AS CAMPAIGN_OBJECT,
        $22 AS CAMPAIGN_ID,
        $23 AS CAMPAIGN_TITLE,
        $24 AS CAMPAIGN_WIZARDSTATUS
    FROM @MAILSHAKE_API.MAIL_API.MAILSHAKE_API_STAGE/merged-created-leads/
)
FILE_FORMAT = (FORMAT_NAME = MAILSHAKE_API.MAIL_API.CSV_FORMAT)
ON_ERROR = 'CONTINUE';
