CREATE OR REPLACE STREAM MAILSHAKE_API.MAIL_API.OPENS_STREAM
ON TABLE MAILSHAKE_API.MAIL_API.ACTIVITY_OPENS
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM MAILSHAKE_API.MAIL_API.CLICKS_STREAM
ON TABLE MAILSHAKE_API.MAIL_API.ACTIVITY_CLICKS
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM MAILSHAKE_API.MAIL_API.CREATED_LEADS_STREAM
ON TABLE MAILSHAKE_API.MAIL_API.ACTIVITY_CREATED_LEADS
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM MAILSHAKE_API.MAIL_API.REPLIES_STREAM
ON TABLE MAILSHAKE_API.MAIL_API.ACTIVITY_REPLIES
APPEND_ONLY = TRUE;

CREATE OR REPLACE STREAM MAILSHAKE_API.MAIL_API.SENT_STREAM
ON TABLE MAILSHAKE_API.MAIL_API.ACTIVITY_SENT
APPEND_ONLY = TRUE;
